import { Download, Code2, Laptop, ArrowUpRight } from "lucide-react";
import { PageIntro, Sources, Breadcrumbs } from "@/components/shared";
import { Button } from "@/components/ui/button";
import { pageMetadata } from "@/lib/metadata";
import { release, site } from "@/lib/site";
export const metadata = pageMetadata("/download/");
export default function DownloadPage() { return <div className="container"><PageIntro label="Get the app" title="Make yourself at home." description="Curtains for your tabs. A robot for your desktop. A native Mac app with room for your own ideas." />
  <section className="release-card"><Laptop size={36} aria-hidden="true" /><div><h2>UnfoldMyMac for Mac</h2><p>macOS {release.minimumMacOS} or later</p>{release.status === "available" && release.assetUrl ? <><Button asChild><a href={release.assetUrl}><Download size={18} aria-hidden="true" />Download UnfoldMyMac {release.version}</a></Button><p className="small">{release.architectures.join(" / ")} · Developer ID signed and Apple notarized</p><p className="small">SHA-256: <code className="checksum">{release.sha256}</code></p></> : <><p className="release-status">The first downloadable release is being prepared.</p><p>You can build from source today. Packaged releases will appear on GitHub once they’re ready.</p><Button asChild variant="secondary"><a href={`${site.repo}/releases`}><Code2 size={18} aria-hidden="true" />View GitHub Releases</a></Button></>}</div></section>
  <div className="download-columns"><section className="prose"><h2>Before you start</h2><ul><li>The app requires macOS 26 or later.</li><li>Automatic lid effects need a MacBook with a readable lid-angle sensor. Model support varies.</li><li>Manual preview remains available without a sensor, subject to built-in display safety checks.</li><li>Frost needs Screen Recording permission. Other lid effects do not.</li><li>Wallpapers can run on external displays.</li></ul><a href="/faq/" className="text-link">More compatibility answers <ArrowUpRight size={16} aria-hidden="true" /></a></section>
  <section className="prose"><h2>{release.status === "available" ? "Install the app" : "When the DMG is ready"}</h2><ol><li>Download the DMG from the verified release link.</li><li>Open it and drag UnfoldMyMac into Applications.</li><li>Launch UnfoldMyMac and choose an effect.</li><li>Try Preview, then turn on lid effects when you’re ready.</li></ol><p>The planned release format is a Developer ID-signed, Apple-notarized DMG. Release signing is not claimed until it has been verified.</p></section></div>
  <section id="build-from-source" className="source-build prose"><h2>Build from source</h2><p>Install Xcode 26 or later with Swift 6.2+, then select Xcode’s command-line tools in Settings → Locations.</p><pre tabIndex={0} role="region" aria-label="Build from source commands"><code>{`git clone https://github.com/satyajiit/UnfoldMyMac.git\ncd UnfoldMyMac/MacDuo\n./script/build_and_run.sh`}</code></pre><p>The script builds and opens <code>MacDuo/dist/UnfoldMyMac.app</code>. It uses an available Apple Development identity or falls back to ad-hoc signing. You can copy the built app to Applications.</p><p>To check the lid hardware, run <code>./script/build_and_run.sh --probe</code> from the same directory.</p></section><Sources /><Breadcrumbs path="/download/" title="Get the app" /></div>; }
