export const faqs = [
  { question: "Which Macs does UnfoldMyMac support?", answer: "The app requires an Apple silicon Mac running macOS 26 or later; there is no Intel build. Automatic lid effects also need a MacBook with a readable lid-angle sensor. The app uses an undocumented Apple HID report, so sensor support varies by model. The repository’s --probe command checks your machine." },
  { question: "Can I try effects without a lid sensor?", answer: "Yes. Manual preview supports playing, pausing, and scrubbing an effect. Built-in display safety checks still apply, so a missing sensor does not bypass closed, asleep, unavailable, or mirrored display restrictions." },
  { question: "Do effects run on an external monitor?", answer: "Lid effects target the MacBook’s built-in display. They pause when that display is closed, asleep, unavailable, or mirrored. Live wallpapers can use external displays." },
  { question: "Why does Frost ask for Screen Recording?", answer: "Frost blurs the live desktop using in-memory ScreenCaptureKit frames. Capture begins only when you enable Frost or start its preview and stops when you switch away. Frames are not saved or transmitted. Other lid effects do not require Screen Recording." },
  { question: "Will the overlay block my clicks?", answer: "No. Effect overlays let clicks through. The Dock and menu-bar controls remain available. Effects start disabled so you can preview a design before enabling it." },
  { question: "Can I use my own artwork?", answer: "Yes. Add an image to the effect library, choose a reveal style, and adjust its depth and edge light. The app stores its own copy. Removing the import deletes that copy and leaves your original file alone." },
  { question: "Are wallpaper data connections required?", answer: "No. Connections are optional. You can connect local Mac metrics, local Claude or Codex metadata, a public GitHub profile, or custom snapshots. Lifecycle hooks require their own setup step." },
  { question: "Are the Grok and racing counters live service data?", answer: "No. Grok’s hot takes and the racing scene’s laps are playful wallpaper-session counters. They do not report Grok usage or live race telemetry. Website wallpaper recordings use sample data." },
  { question: "Does the app respect Reduce Motion?", answer: "Yes. Reduce Motion stills continuous animation while manual and lid control remain available. Reduce Transparency uses a dim-only effect without desktop capture. Wallpaper playback also adapts to sleep and low-power conditions." },
  { question: "Is this the iPhone Duo effect for Mac?", answer: "It is the idea, rebuilt for a MacBook. Frost started as an attempt to bring the iPhone Duo frost to the Mac, and the rest of the effects grew from there. It is not Apple\u2019s code, it is not a port, and the app is not affiliated with or endorsed by Apple. On a Mac the trigger is the lid angle rather than a fold, so the timing is yours to tune." },
  { question: "Can I get an iOS Duo-style wallpaper effect on macOS?", answer: "Yes. Frost blurs the live desktop as the lid closes, and Art Reveal, Curtains and Peekaboo give you other ways to hand the screen off. Live wallpapers run independently of the lid, so you can pair an iOS Duo-style close with a wallpaper that keeps moving while the Mac is open." },
  { question: "Is UnfoldMyMac open source?", answer: "Yes. The source is published under Apache 2.0. Space Grotesk keeps its SIL Open Font License, and third-party product marks retain their owners’ rights. The repository includes the full license and notices." },
];
