import { CreativeScenesSection } from "@/components/creative-scenes";
import Image from "next/image";
import Link from "next/link";
import { SlidersHorizontal, ImagePlus, MousePointer2, Accessibility, Monitor, Cpu, Code2 } from "lucide-react";
import { PageIntro, DownloadCTA, Sources, Breadcrumbs } from "@/components/shared";
import { pageMetadata } from "@/lib/metadata";
import { lockScreenGuide } from "@/components/lock-screen-section";
import { site, sources } from "@/lib/site";
export const metadata = pageMetadata("/features/");
const details = [
  { Icon: SlidersHorizontal, title: "Your timing", text: "Browse Glass & Light, Motion & 3D, or Image Art. Use Adjust for grouped appearance controls and creator details. Set the lid angle where the effect begins and how far into closing it finishes. Preview, pause, and scrub before turning it on." },
  { Icon: ImagePlus, title: "Your artwork", text: "Import an image, then choose Sculpted, Diagonal, Slide, or Burst. Adjust depth and edge light. The app keeps a local copy." },
  { Icon: MousePointer2, title: "Your desktop still works", text: "Overlays let clicks through. Effects start disabled, and the Dock and menu-bar controls stay available." },
  { Icon: Accessibility, title: "Your preferences", text: "System, light, and dark appearance. Reduce Motion stills continuous animation; Reduce Transparency uses dimming without capture." },
];
export default function FeaturesPage() { return <div className="container"><PageIntro label="Features" title="Made for the way you open your Mac." description="Lid Effects for a physical gesture. Dynamic Wallpapers for a living desktop. Creative Scenes for worlds that respond to your Mac." />
  <section id="lid-effects" className="feature-story"><Image src="/media/curtains.webp" alt="Curtains effect artwork" width={1000} height={667} sizes="(max-width: 800px) 90vw, 560px" /><div><span className="section-context">Lid Effects</span><h2>A curtain call.<br />Every time you close.</h2><p>Close your MacBook and the curtains meet across the desktop. Open it and they pull apart. Or pick blur, glowing ribbons, blinking characters, and artwork that moves with the lid.</p><p>Frost began as an attempt to bring the iPhone Duo blur to a MacBook. The gesture is different — a lid angle rather than a fold — so the blur follows how far you have actually closed it, at whatever speed you close it.</p><p>Effects follow the built-in display. Lid control needs a readable angle sensor; support varies by MacBook model.</p><Link href="/faq/" className="text-link">Check compatibility</Link></div></section>
  <div className="feature-detail-grid">{details.map(({ Icon, title, text }) => <section key={title}><Icon size={25} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></section>)}</div>
  <section id="wallpapers" className="feature-story reverse"><Image src="/media/pulse.webp" alt="Pulse wallpaper with a chrome sculpture and sample Mac metrics" width={1000} height={625} sizes="(max-width: 800px) 90vw, 560px" /><div><span className="section-context">Dynamic Wallpapers</span><h2>A desktop with<br />something to do.</h2><p>Browse twenty wallpapers in a grid or list, with category tabs and tag filters. Open a design to see its description, creator credits, and connection badges. Preview the actual design, then select Use wallpaper below it. Wallpapers run on your primary display at 30 or 60 fps, with playback adapting to sleep, low power, and Reduce Motion. On macOS 26, System Settings › Wallpaper can assign a scene to each display.</p><p>Connect Mac metrics, local Claude or Codex activity, a public GitHub profile, or your own JSON data. Ten game worlds add battery recovery, network traffic, focus and break timers, thermal pressure, storage, city weather, and public Steam updates. Choose Customize on the design page for its data connections and appearance. The app asks for any required setup before applying a design.</p><p>GTA VI — Vice City Countdown pairs Rockstar Games promotional artwork with a calendar-day countdown, as a tribute rather than an official tie-in. Aurora Observatory wraps a 3D Earth in auroras driven by public NOAA forecasts, with imagery from NASA Earth Observatory.</p><Link href="/blog/connecting-your-data/" className="text-link">How data connections work</Link></div></section>
  <CreativeScenesSection />
  <section id="lock-screen" className="feature-story reverse"><Image src="/media/lock-screen.webp" alt="A macOS lock screen showing the time over the Ghost of Tsushima — Scarlet Wind wallpaper, with maple leaves blowing across a moonlit valley" width={1920} height={1200} sizes="(max-width: 800px) 90vw, 560px" /><div><span className="section-context">Lock screen</span><h2>Lock it.{" "}<br />It keeps going.</h2><p>On macOS 26, UnfoldMyMac installs a wallpaper provider extension. Every bundled Dynamic Wallpaper and Creative Scene, Hinge Garden and The Workshop included, appears in System Settings under UnfoldMyMac — Dynamic Wallpapers. It shows in both the Wallpaper and Screen Saver panes, with a rendered thumbnail.</p><p>The lock screen and the screen saver share one selection in macOS. Choose a scene under Screen Saver and it plays on your lock screen: the same Metal scene, the same live readouts while the app is running, at up to 60 fps. macOS composites it, so it keeps going with the app closed and comes back at login. Lid, sound, and pointer reactions stay with the app’s own desktop window.</p><p>The app shows where a scene is showing, desktop only or desktop and lock screen, and Add to Lock Screen… in the menu bar opens the Screen Saver pane. It never picks the provider for you; you choose.</p><p className="small muted">Illustration: Ghost of Tsushima — Scarlet Wind behind a macOS lock screen layout. Sample data. Official logo © Sucker Punch Productions / Sony Interactive Entertainment.</p><Link href={lockScreenGuide} className="text-link">How the lock screen works</Link></div></section>
  <div className="feature-detail-grid three-columns"><section><Monitor aria-hidden="true" /><h3>Different jobs for different displays</h3><p>Lid effects stay on your MacBook’s built-in display and pause when it is closed, asleep, unavailable, or mirrored. Choosing Use wallpaper draws a scene on your primary display; other displays keep the wallpaper you chose for them. On macOS 26, System Settings › Wallpaper assigns a scene per display, and Screen Saver puts one on the lock screen.</p></section><section><Cpu aria-hidden="true" /><h3>Native from the first frame</h3><p>Built with SwiftUI, AppKit, and Metal. Frost uses ScreenCaptureKit for in-memory desktop frames. Other lid effects do not need Screen Recording. The wallpaper extension runs in the App Sandbox with no network, microphone, or file-access entitlements.</p></section><section><Code2 aria-hidden="true" /><h3>Open source, Apache 2.0</h3><p>The Swift app, its Metal shaders, and this website are public on <a href={site.repo}>GitHub</a>. Read the code, report a bug, or build your own template with the <a href={sources.developing}>extension guide</a>. Free, and not monetized.</p></section></div><Sources /><DownloadCTA /><Breadcrumbs path="/features/" title="Features" /></div>; }
